### ISSUE TITLE
Swan Crystal not drawing to half of screen

### ISSUE THREAD

**Issue by hadn69** [WonderfulToolchain/ws-bootfriend#3]
So I flashed BootFriend to my Swan Crystal and its now not drawing to half the screen. I also chose the "SwanCrystal TFT recovery".
![20230216_212559](https://user-images.githubusercontent.com/2972930/219557492-b8e7e248-e1ed-4005-b4fc-3e3432a8d887.JPG)

**Comment by hadn69** [comment]
Also is the eerpom backed up in save data okay flash back?

**Comment by asiekierka** [comment]
The internal EEPROM backed up in the save data should be okay to flash back. I have also pushed a fixed version of bootfriend-inst (should say `bootfriend-inst02` when loaded on a console) which should improve the behaviour of the "SwanCrystal TFT recovery" option; please report back!

Two questions:

1. Did the display work fine after installing BootFriend, but before performing TFT recovery? (Assuming you did a reboot between the two, of course. The TFT is only reconfigured on a reboot.)
2. Could you provide me with the dump of the internal EEPROM from save data for additional research/verification purposes? (I've reached out to you on Discord.)

**Comment by hadn69** [comment]
1. The display behaved like this after a reboot but before TFT recovery.
2. I sent you the file on discord but its on here as well.
[eeprom.zip](https://github.com/WonderfulToolchain/ws-bootfriend/files/10770883/eeprom.zip)

**Comment by hadn69** [comment]
So flashed the new version and it seems to work after completing TFT recovery. Will test further.
