### ISSUE TITLE
Web UI name color selection not applying.

### ISSUE THREAD

**Issue by hadn69** [WonderfulToolchain/ws-bootfriend#5]
Was changing my boot splash and I noticed the name color I chose in the web UI is not what is flashed. 
Desired result: 
![firefox_Bsv2bt68HQ](https://user-images.githubusercontent.com/2972930/220330233-5ba1cbe7-0c24-4b64-91cd-f6e270e86ff8.png)
Actual result:
![20230221_031036](https://user-images.githubusercontent.com/2972930/220330490-ef290911-714a-4087-b547-1e6b77dc4d7b.JPG)

The file I flashed is [bootfriend-inst.zip](https://github.com/WonderfulToolchain/ws-bootfriend/files/10792907/bootfriend-inst.zip)

**Comment by asiekierka** [comment]
BootFriend v01 regression; will close issue when it's pushed on web (there's a blocking feature I want to add this time around).

**Comment by asiekierka** [comment]
Fixed.
